services:
  backend:
    build:
      context: ./backend
    container_name: streaker-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/streaker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - streaker-net

  db:
    image: postgres:15
    container_name: streaker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: streaker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - streaker-net

volumes:
  pgdata:

networks:
  streaker-net: