services:
  backend:
    build:
      context: ./backend
    container_name: streaker-backend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - streaker-net
    volumes:
      - shared-logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15
    container_name: streaker-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: streaker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - streaker-net

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: streaker-fluent-bit
    volumes:
      - ./logging/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./logging/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - shared-logs:/app/logs
    depends_on:
      - loki
    networks:
      - streaker-net

  loki:
    image: grafana/loki:2.9.2
    container_name: streaker-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./logging/loki/config.yaml:/etc/loki/config.yaml
    networks:
      - streaker-net

  grafana:
    image: grafana/grafana:latest
    container_name: streaker-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./logging/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - streaker-net

  redis:
    image: redis:7.4
    container_name: streaker-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - streaker-net
    restart: unless-stopped

volumes:
  pgdata:
  shared-logs:

networks:
  streaker-net:
