services:
  backend:
    build:
      context: ./backend
    container_name: streaker-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/streaker
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - streaker-net
    volumes:
      - shared-logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15
    container_name: streaker-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: streaker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - streaker-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HEC
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: changeme123
    volumes:
      - splunk-data:/opt/splunk/var
      - shared-logs:/logs   # Shared with backend
    networks:
      - streaker-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata:
  shared-logs:
  splunk-data:

networks:
  streaker-net: