name: Bump Versions

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  detect-and-bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release
        run: |
          npm install --no-save semantic-release \
            @semantic-release/git \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/exec

      - name: Make bump script executable
        run: chmod +x infra/scripts/.bump-version.sh

      - name: Detect changes and bump accordingly
        run: |
          git fetch origin main --depth=2
          CHANGED_FILES=$(git diff --name-only origin/main~1..origin/main)
          echo "Changed files: $CHANGED_FILES"

          HAS_FRONTEND_CHANGES=false
          HAS_BACKEND_CHANGES=false

          for file in $CHANGED_FILES; do
            if [[ $file == frontend/* ]]; then
              HAS_FRONTEND_CHANGES=true
            elif [[ $file == backend/* ]]; then
              HAS_BACKEND_CHANGES=true
            fi
          done

          if [[ "$HAS_FRONTEND_CHANGES" == true ]]; then
            echo "Running frontend semantic-release"
            npx semantic-release --extends .releaserc.frontend.json
          fi

          if [[ "$HAS_BACKEND_CHANGES" == true ]]; then
            echo "Running backend semantic-release"
            npx semantic-release --extends .releaserc.backend.json
          fi

          # Always run global release last to tag the commit
          echo "Running global semantic-release"
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
