name: Bump Version on Merge

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push tags

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release and plugins
        run: |
          npm install --no-save \
            semantic-release \
            @semantic-release/git \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/exec

      - name: Ensure VERSION file exists
        run: |
          test -f VERSION || echo "0.1.0" > VERSION

      - name: Make bump-version script executable
        run: chmod +x .bump-version.sh

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
