name: Sync main to staging

on:
  push:
    branches:
      - main

jobs:
  sync-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # Needed to push to another branch

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Force push main to staging
        run: |
          git push origin main:staging --force
